import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "do it",
  description: "Generated by create t3 app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html className={`${inter.variable}`} lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
